# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# 06/25/2021 09:57 pm - SSN - Redo after adding solution file

#trigger:
# batch: true

schedules:
- cron: "*/5 * * * *"
  branches:
   include:
    - main
    - test-build-branch

pool:
  name: ssn-self-hosted-pool-20210604

  
variables:
  buildConfiguration: 'Release'

jobs:
 - job: Compile
   displayName: 'Compile the code'
   pool:
    name: ssn-self-hosted-pool-20210604
   steps:
   - script: dotnet build --configuration $(buildConfiguration)
     displayName: 'dotnet build $(buildConfiguration)'
 - job: TestSuite1
   displayName: 'Execute test suite 1'
   dependsOn: Compile
   pool:
       name: ssn-self-hosted-pool-20210604
   steps:
    - script: dotnet test "$(Build.SourcesDirectory)\testproj\testproj.csproj" --filter TestCategory=Suite1
      displayName: 'Running tests - Suite1'
 - job: TestSuite2
   displayName: 'Execute test suite 2'
   dependsOn: Compile
   pool:
       name: ssn-self-hosted-pool-20210604
   steps:
    - script: dotnet test "$(Build.SourcesDirectory)\testproj\testproj.csproj" --filter TestCategory=Suite2
      displayName: 'Running tests - Suite2'

